# .travis.yaml

language: python

sudo: true

env:
  - LUA_VERSION="5.1" LUAROCKS_VERSION="3.0.2" KONG_VERSION="2.0.3-0" LUA_RESTY_OPENIDC_VERSION="1.6.1-1"

script:
  - sudo -E bash ci/root.sh
  - . ci/setup.sh
  - . ci/run.sh

after_success:
  - luarocks install luacov-coveralls
  - luacov-coveralls

